name: Test and Deploy 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: cd server/ && npm test -v  

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Netlify netlify/actions/cli
        run: npm install -g netlify-cli
      - name: Install back end deps
        run: cd server/ && npm install
      - name: Install frontend deps
        run: cd client/ && npm install
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy
        run: netlify deploy --alias dev
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
