name: Test and Deploy 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up node js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies and run tests
      run: |
       cd server/
       npm install
       npm test -v  
          

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build and deploy to Render
        run: |
          cd client/
          npm install
          npm run build
          cd ../server/
          npm install
          render deploy --build-command "npm run build"
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN}}
